# Required
version: 2

# Sphinx
sphinx:
  fail_on_warning: false

# Build
build:
  os: "ubuntu-22.04"
  tools:
      python: "mambaforge-4.10"

# Conda
conda:
    environment: env/environment.rtd.yml

